name: hungrybelt
description: "Food Dashboard Application - A one-stop shop for mealtime dilemmas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.2 
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.0
  get: ^4.6.6
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/

